/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parkingmeterGUI.View;

import parkingmeterGUI.Model.ParkingMeter;

/**
 *
 * @author stone
 */
public class ParkingMeterView extends javax.swing.JFrame {

    /**
     * Creates new form ParkingMeterView
     */
    private final ParkingMeter parkingMeter;
    private int cont = 0;
    public ParkingMeterView() {
        initComponents();
        this.parkingMeter = new ParkingMeter(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpOne = new javax.swing.JPanel();
        jlIcon = new javax.swing.JLabel();
        jpTwo = new javax.swing.JPanel();
        jlBalance = new javax.swing.JLabel();
        jtBalance = new javax.swing.JTextField();
        btnInsert = new javax.swing.JButton();
        jpThree = new javax.swing.JPanel();
        jlBalanceInsert = new javax.swing.JLabel();
        jlTimeChosse = new javax.swing.JLabel();
        jtBalanceInsert = new javax.swing.JTextField();
        jtTimeChosse = new javax.swing.JTextField();
        btnTime = new javax.swing.JButton();
        jpFour = new javax.swing.JPanel();
        btnPrinter = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTicket = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpOne.setBackground(new java.awt.Color(255, 102, 102));
        jpOne.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jlIcon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parkingmeterGUI/Assets/parkingmeter_icon.png"))); // NOI18N
        jlIcon.setText("Parquímetro");
        jlIcon.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jpOneLayout = new javax.swing.GroupLayout(jpOne);
        jpOne.setLayout(jpOneLayout);
        jpOneLayout.setHorizontalGroup(
            jpOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpOneLayout.setVerticalGroup(
            jpOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
        );

        jpTwo.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Entrada de Dinheiro", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jlBalance.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlBalance.setText("Valor");

        jtBalance.setColumns(10);

        btnInsert.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnInsert.setText("Inserir");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpTwoLayout = new javax.swing.GroupLayout(jpTwo);
        jpTwo.setLayout(jpTwoLayout);
        jpTwoLayout.setHorizontalGroup(
            jpTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTwoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlBalance)
                .addGap(18, 18, 18)
                .addComponent(jtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInsert)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpTwoLayout.setVerticalGroup(
            jpTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTwoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsert))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpThree.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Display", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jlBalanceInsert.setText("Valor inserido");

        jlTimeChosse.setText("Tempo escolhido");

        jtBalanceInsert.setColumns(10);

        jtTimeChosse.setColumns(10);

        btnTime.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnTime.setText("Tempo");
        btnTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpThreeLayout = new javax.swing.GroupLayout(jpThree);
        jpThree.setLayout(jpThreeLayout);
        jpThreeLayout.setHorizontalGroup(
            jpThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpThreeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlTimeChosse)
                    .addComponent(jlBalanceInsert))
                .addGap(18, 18, 18)
                .addGroup(jpThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtBalanceInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtTimeChosse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnTime, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jpThreeLayout.setVerticalGroup(
            jpThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpThreeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTime, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addGroup(jpThreeLayout.createSequentialGroup()
                        .addGroup(jpThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlBalanceInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtBalanceInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlTimeChosse)
                            .addComponent(jtTimeChosse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpFour.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Ticket", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        btnPrinter.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnPrinter.setText("Imprimir");
        btnPrinter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrinterActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jtTicket);

        javax.swing.GroupLayout jpFourLayout = new javax.swing.GroupLayout(jpFour);
        jpFour.setLayout(jpFourLayout);
        jpFourLayout.setHorizontalGroup(
            jpFourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFourLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPrinter, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpFourLayout.setVerticalGroup(
            jpFourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFourLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpFourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(btnPrinter, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpTwo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpThree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpFour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jpTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpThree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpFour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        double balance = Double.valueOf(this.jtBalance.getText());
        this.parkingMeter.setBalance(balance);
        this.jtBalanceInsert.setText(String.format("%.2f",this.parkingMeter.getBalance()));
        this.jtBalance.setText("");
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimeActionPerformed
        if(this.cont == 5){
            this.cont = 0; 
        }else{
            this.jtTimeChosse.setText(String.format("%d",this.parkingMeter.chosseTicket(this.cont)));
            this.cont+=1;
        }
    }//GEN-LAST:event_btnTimeActionPerformed

    private void btnPrinterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrinterActionPerformed
       this.jtTicket.setText(this.parkingMeter.ToString(this.cont));
    }//GEN-LAST:event_btnPrinterActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnPrinter;
    private javax.swing.JButton btnTime;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlBalance;
    private javax.swing.JLabel jlBalanceInsert;
    private javax.swing.JLabel jlIcon;
    private javax.swing.JLabel jlTimeChosse;
    private javax.swing.JPanel jpFour;
    private javax.swing.JPanel jpOne;
    private javax.swing.JPanel jpThree;
    private javax.swing.JPanel jpTwo;
    private javax.swing.JTextField jtBalance;
    private javax.swing.JTextField jtBalanceInsert;
    private javax.swing.JTextPane jtTicket;
    private javax.swing.JTextField jtTimeChosse;
    // End of variables declaration//GEN-END:variables
}
