/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quiz.Model.View;

import javax.swing.JOptionPane;
import quiz.Model.Quiz;

/**
 *
 * @author stone
 */
public class QuizGUI extends javax.swing.JFrame {

    /**
     * Creates new form QuizGUI
     */
    private final Quiz quiz;
    private int index = 0;
    public QuizGUI() {
        initComponents();
        this.quiz = new Quiz();
        this.jtxt_area.setText(this.quiz.getAttualyAffirmation(index).getText());
        this.jtxt_area.setFocusable(false);
        this.jl_affirmation.setText(String.format("Afimação: %d de %d",this.index+1, this.quiz.getTotallyAfirmation()));
        this.index+=1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxt_area = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jrb_true = new javax.swing.JRadioButton();
        jrb_falso = new javax.swing.JRadioButton();
        jl_affirmation = new javax.swing.JLabel();
        btn_next = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Quiz de história e atualidades");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Analise a seguinte afirmação:");

        jtxt_area.setColumns(20);
        jtxt_area.setRows(5);
        jScrollPane1.setViewportView(jtxt_area);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Essa afirmação é:");

        jrb_true.setSelected(true);
        jrb_true.setText("Verdadeira");
        jrb_true.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_trueActionPerformed(evt);
            }
        });

        jrb_falso.setText("Falsa");
        jrb_falso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_falsoActionPerformed(evt);
            }
        });

        jl_affirmation.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jl_affirmation.setText("Afirmação");

        btn_next.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_next.setText("Próxima");
        btn_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jl_affirmation))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                                .addComponent(jrb_true)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jrb_falso))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(btn_next)))
                        .addGap(25, 25, 25))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jrb_falso)
                    .addComponent(jrb_true))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_affirmation)
                    .addComponent(btn_next))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrb_falsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_falsoActionPerformed
        this.jrb_true.setSelected(false);
    }//GEN-LAST:event_jrb_falsoActionPerformed

    private void jrb_trueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_trueActionPerformed
        // TODO add your handling code here:
        this.jrb_falso.setSelected(false);
    }//GEN-LAST:event_jrb_trueActionPerformed

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
        if(this.index < this.quiz.getTotallyAfirmation()){
            this.jtxt_area.setText("");
            this.jtxt_area.setText(this.quiz.getAttualyAffirmation(index).getText());
            this.jl_affirmation.setText(String.format("Afimação: %d de %d",this.index+1, this.quiz.getTotallyAfirmation()));
            
            if(this.jrb_true.isSelected() && this.quiz.getAttualyAffirmation(index).isChosse() == true){
                this.quiz.answerAffirmation("hit");
            }else if(this.jrb_falso.isSelected() && this.quiz.getAttualyAffirmation(index).isChosse() == false){
                this.quiz.answerAffirmation("hit");
            }
            else{
                this.quiz.answerAffirmation("mistake");
            }
            
            this.index+=1;
        }
        if(this.index == 6){
            if(this.jrb_true.isSelected() && this.quiz.getAttualyAffirmation(index).isChosse() == true){
                this.quiz.answerAffirmation("hit");
            }else if(this.jrb_falso.isSelected() && this.quiz.getAttualyAffirmation(index).isChosse() == false){
                this.quiz.answerAffirmation("hit");
            }
            else{
                this.quiz.answerAffirmation("mistake");
            }
        }
        if(this.index == this.quiz.getTotallyAfirmation()){
            JOptionPane.showMessageDialog(this, "Voce acertou "+ this.quiz.getTotallyHits()+" e errou "+this.quiz.getTotallyMistakes());
        }
    }//GEN-LAST:event_btn_nextActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_next;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jl_affirmation;
    private javax.swing.JRadioButton jrb_falso;
    private javax.swing.JRadioButton jrb_true;
    private javax.swing.JTextArea jtxt_area;
    // End of variables declaration//GEN-END:variables
}
